### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Alireza1379dev** [mlvl42/termux_python#6]
Hi
I have a problem

![code](https://user-images.githubusercontent.com/81929593/175190144-423a195a-048c-41a0-baff-c099a57cdaba.jpg)

![error](https://user-images.githubusercontent.com/81929593/175189797-7b6cb131-8368-41e0-8e7b-88f3514137c0.jpg)

File "/data/data/com.termux/files/home/python/Telemux/termux_python/termux/termux.py", line 2, in <module>
    from termux.common import utils
ModuleNotFoundError: No module named 'termux.common'

I changed it to from .common import utils and the problem was fixed

**Comment by Alireza1379dev** [comment]
Sorry
The module is not installed

**Comment by mlvl42** [comment]
Hi,

This package can be installed this way:
```
git clone https://github.com/mlvl42/termux_python
cd termux_python
python3 setup.py install
```

Then, you should be able to import the functions like so:
```python
from termux import battery_status
battery_status()
```

I have not created a pip package for this project since I have not put a lot of work into it + I very rarely use termux.

**Comment by mlvl42** [comment]
Well, I just published a release on pypi and added install instructions + example usage in the project README (cf https://github.com/mlvl42/termux_python/commit/fab8a1e662732bb299435b95157a5ddcf1dc5721).
I am closing this but don't hesitate to create other issues if you encounter a problem.
